#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Aug 14 17:58:19 2018

@author: hajime
"""
import tensorflow as tf
with tf.Session() as sess:
    x=tf.range(0,10)
    print(sess.run(x[1:]))
    env = tf.random_normal([1,20],dtype=tf.float64)
    env_abs = tf.abs(env)
    print(sess.run(env_abs))