#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Aug 14 11:10:04 2018

@author: hajime
"""
from matplotlib import pyplot as plt

import pickle
import numpy as np

res = pickle.load( open("orgA_res.pickle","rb")  )

iterations = len(res)
fig, ax = plt.subplots()
ax.plot([1],[1])
ax.set_xlim(0,iterations)
ax.set_ylim(np.min(res),np.max(res))
ax.set_ylabel("Welfare")
ax.set_xlabel("Training Epoch")
ax.plot(np.arange(len(res)), res,".")
